export const flightEvents = {
    'GET_FLIGHTS_DONE': 'GET_FLIGHTS_DONE',
    'GET_PLACES_DONE': 'GET_PLACES_DONE',
    'SET_BOOKING_DONE': 'SET_BOOKING_DONE',
    'GET_BOOKING_DONE': 'GET_BOOKING_DONE'
}
export const userEvents = {
    'SET_USER_DONE': 'SET_USER_DONE',
    'UPDATE_USER_DONE': 'UPDATE_USER_DONE',
    'GET_LOGIN_DONE': 'GET_LOGIN_DONE'
}

